### ISSUE TITLE
Add to_s method to XDM nodes for convenience.

### ISSUE THREAD

**Issue by pobocks** [fidothe/saxon-rb#10]
Having a "this -> string representation" method for XDM::Node objects seems like it would make working with the library easier, and as far as I can tell,

```
xdm_node.to_java.to_s
```

does the right thing, though I wouldn't feel competent to say it was reasonable to do from a performance standpoint.

There might be other methods that are useful to forward, or in the limit even a general "if it's not defined on me, forward to java object" might be appropriate?  I feel like that would require investigation time and a critical eye, but I think the to_s is useful enough that I'm willing to positively advocate it.

**Comment by fidothe** [comment]
Funny you should bring this up. You're quite right, that being able to call `to_s` on an `XDM::Node` would make sense. The problem (and why I've been holding off on this), is the principle of least surprise. 

If your XDM tree was created by a `Saxon::DocumentBuilder`, e.g. from a bytestream of XML, the calling `to_s` on a Node produces what you'd expect.

If however, your XDM tree was created by an XSLT transformation, then XSLT serialization has not yet occured, and if your XSLT uses `<xsl:output>` with things like `<xsl:character-map>` then those things are applied during serialization, not before.

So, if you call `to_s` on a node in such a tree then you may not get the string you were expecting, which, if it happens, is extraordinarily hard to understand unless you know exactly what you're looking for (ask me how I know 😭).

I'm still not sure what to do about that. It's not common, but it's extremely painful if it happens to you.

In the first instance, it was waiting for me to properly wrap `net.sf.saxon.s9api.Serializer`, which happened a couple of weeks back. 

Now it's waiting for me to figure out if there's a way to easily and inexpensively detect if something like `<xsl:character-map>`s are in use, so I understand what the options are available to me are.

I think the set of options is going to work out something like this:

1. just call the underlying `toString` method on XdmNode, and if you step on the landmine, sucks to be you.
2. If the XDM tree was produced by an XSLT, then `XDM::Node#to_s` checks if it's a potentially dangerous one, and if so then the node serialization is done using a `Serializer` that respects the `<xsl:output>` options in play, minus outputting the XML declaration.
3. Just ('Just') make potentially dangerous transforms serialize and re-parse their output if you try and get an XDM tree out of them.

More generally, I'm pretty careful to provide a trapdoor into Saxon-Java-land through `#to_java`, so if there's stuff people need to do, they can do it. If there's stuff that's used often enough (i.e. somone asks about it), or where an idiomatic Ruby approach would be much more pleasant, then that's what gets first-class-citizen wrapping.

**Comment by pobocks** [comment]
Urgh, sorry, I should have considered before suggesting "simple commonsense thing" that it would have been in there if it was just that easy :-)

What do you think about maybe documenting the general nature of `to_java` (i.e. "It's generally a handle to the underlying Saxon API object") and some examples of a few common XML tasks (with caveats) in the README, and a pointer to the Saxon docs?

**Comment by fidothe** [comment]
FWIW I'm still thinking seriously about adding an Destination::XDM-a-like that serializes and re-builds the XDM tree for people who need/want this kind of transform in the middle of a sequence of transforms or other processing...
